import argparse
import numpy as np
import torch
import json
import random
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path

from train_cifar import train as train_cifar
from train_mnist import train as train_mnist


@dataclass
class RunConfig:
    dataset: str
    model: str
    optimizer: str
    epochs: int
    batch_size: int
    lr: float
    lr_aux: float
    momentum: float
    nesterov: bool
    lambda_mult: float
    ns_steps: int
    norm_weight: bool   
    weight_decay: float | None
    seed: int
    device: str
    data: str
    download: bool
    run_name: str

def get_params():
    p = argparse.ArgumentParser()
    p.add_argument("--dataset", type=str, required=True, choices=["mnist", "cifar10"])
    p.add_argument("--model", type=str, default="cnn2", choices=["cnn2", "resnet9", "resnet18"]) 
    p.add_argument("--optimizer", type=str, default="signmuon", choices=["signmuon", "ef_usignmuon", "ef_udsignmuon", "muon", "signsgd", "sgd", "adam"])
    p.add_argument("--data", type=str, default="./data")
    p.add_argument("--download", action="store_true", help="Download dataset if missing")
    p.add_argument("--device", type=str, default="cpu")
    p.add_argument("--seed", type=int, default=0)

    p.add_argument("--epochs", type=int, default=10)
    p.add_argument("--batch-size", type=int, default=128)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--lr-aux", type=float, default=1e-3)
    p.add_argument("--momentum", type=float, default=0.9)
    p.add_argument("--nesterov", action="store_true")
    p.add_argument("--lambda-mult", type=float, default=1.0)
    p.add_argument("--ns-steps", type=int, default=5)
    p.add_argument("--norm_weight", action='store_true', default=False)
    p.add_argument("--weight-decay", type=float, default=5e-4, help="Only used for CIFAR with Adam/SGD")

    p.add_argument("--run-name", type=str, default="", help="Folder name in ./saves/ , if empty, autogenerated")
    return p


def seed_everything(seed):
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def save_run(
    model: torch.nn.Module,
    history: dict,
    config: RunConfig,
):
    saves_root = Path(__file__).resolve().parent / "saves"
    saves_root.mkdir(parents=True, exist_ok=True)

    run_dir = saves_root / config.run_name
    if run_dir.exists():
        shutil.rmtree(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    ckpt = {
        "model_state_dict": model.state_dict(),
        "config": asdict(config),
    }
    torch.save(ckpt, run_dir / "model.pt")

    with open(run_dir / "metrics.json", "w", encoding="utf-8") as f:
        json.dump({"config": asdict(config), "history": history}, f, indent=2)

    return run_dir


def main() -> None:
    args = get_params().parse_args()

    seed_everything(args.seed)

    if not args.run_name:
        args.run_name = f"{args.dataset}_{args.model}_{args.optimizer}"

    # params
    print("parse params...")
    config = RunConfig(
        dataset=args.dataset,
        model=args.model,
        optimizer=args.optimizer,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        lr_aux=args.lr_aux,
        momentum=args.momentum,
        nesterov=bool(args.nesterov),
        lambda_mult=args.lambda_mult,
        ns_steps=args.ns_steps,
        weight_decay=(args.weight_decay if args.dataset == "cifar10" else 0.0),
        norm_weight=args.norm_weight,
        seed=args.seed,
        device=args.device,
        data=args.data,
        download=bool(args.download),
        run_name=args.run_name,
    )

    # train
    device = torch.device(args.device)
    if args.dataset == "mnist":
        print("Train MNIST...")
        model, history = train_mnist(args)
    else:
        print("Train CIFAR...")
        model, history = train_cifar(args)

    model.to("cpu")

    run_dir = save_run(model, history, config)
    print(f"Saved run to: {run_dir}")


if __name__ == "__main__":
    main()